name: Checkpoint

on:
  pull_request:

permissions:
  contents: read

jobs:
  # Review
  review:
    name: Review
    uses: ./.github/workflows/reusable.review
  # CodeQL
  codeql:
    name: CodeQL
    permissions:
      # read
      actions: read
      contents: read
      packages: read
      # write
      security-events: write
    uses: ./.github/workflows/reusable.codeql
  # Scorecard
  scorecard:
    name: Scorecard
    permissions:
      # read
      actions: read
      checks: read
      contents: read
      issues: read
      pull-requests: read
      # write
      id-token: write
      security-events: write
    uses: ./.github/workflows/reusable.scorecard
  # Test
  test:
    name: Test
    uses: ./.github/workflows/reusable.test
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
