name: Security

on:
  push:
    branches-ignore:
      - '[0-9].[0-9].x'
      - '[0-9].x.x'
      - '[0-9].x'
      - main
      - next
      - rc
      - beta
      - alpha

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [javascript, typescript]
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Analyze CodeQL
        uses: github/codeql-action/analyze@v3

      - name: Analyze OSSF Scorecard
        uses: ossf/scorecard-action@v2.4.1
        with:
          results_file: ossf_scorecard.sarif
          results_format: sarif
          repo_token: ${{ secrets.TOKEN }}
          publish_results: true

      - name: Upload to GitHub Actions Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSSF Scorecard
          path: ossf_scorecard.sarif

      - name: Upload to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ossf_scorecard.sarif